default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  user: <%= ENV["DB_USER"] %>

development:
  <<: *default
  database: grphql-srvr_dev

test:
  <<: *default
  database: grphql-srvr_test

production:
  <<: *default
  database: grphql-srvr_production
  username: grphql-srvr
  password: <%= ENV['GRPHQL-SRVR_DATABASE_PASSWORD'] %>
